# The URL is presented over the config API
url: https://foobar.example.com
adminemail:
  # These addresses are presented over the config API
  - admin1@example.com
  - admin2@example.net
dns: # DNS service providers
  providers:
    infblxA: # Infoblox NIOS over WAPI
      type: infoblox
      name: Infoblox A
      host: foo.bar2.local
      port: 443
      version: 2.10 #WAPI version to use
      dnsview: my-dnsview # The DNS view configured in Infoblox
      auth: #endpoint specific
        user: username
        pass: password
      # sslverify: "false" #only set this in case cert validation shall be disabled
    infblxB:
      type: infoblox
      name: Infoblox B
      host: foo.bar.local
      port: 1234
      version: 2.8
      dnsview: my-dnsview
      auth:
        user: username
        pass: password
      #sslverify: "false"
    dns3l:
      type: otc # Open Telekom Cloud (OTC) DNS
      name: DNS3L Labs Inc. OTC tenant
      auth:
        authurl: https://iam.eu-de.otc.t-systems.com/v3
        projectname: #omitted
        projectid: #omitted
        ak: accesskeyID
        sk: secretaccesskey
      os-region: eu-de
      precheck:
        enabled: true
        checkNameservers:
          # These nameservers are used to check if and when the DNS entries are propagated
          # so the ACME provider can read the challenges
          - 1.2.3.4:53
          - 5.6.7.8:53
        precheckInterval: 2s
        precheckTimeout: 2m
# somepdns:
#   type: pdns # PowerDNS AS
#   ...
ca: #ACME and none ACME CA
  providers:
    le: #Add least /directory to endpoint URL
      type: acme
      name: Let's Encrypt
      catype: public
      api: https://acme-v02.api.letsencrypt.org/directory
      url: https://letsencrypt.org
      roots: https://letsencrypt.org/certificates/
      description: "Let's Encrypt Official"
      logopath: "/images/logo.png"
      daysRenewBeforeExpiry: 30
    tsec-staging:
      type: acme
      name: T-Sec Trust Center ACME Staging
      catype: public
      api: https://acme.npp.test.telesec.de/v2/directory
      url: https://www.telesec.de
      auth:
        # EAB is currently not implemented
        account: Account Id
        key: EAB KeyId
        hmac: EAB HMAC
      roots: https://www.telesec.de/en/root-program/root-program/overview/
      description: "Telesec Trust Center ACME Staging"
      logopath: "../logo.png"
      daysRenewBeforeExpiry: 30
      httpInsecureSkipVerify: true #if TLS cert check shall be disabled
      acmeRegisterWithoutEmail: true # if registration of new ACME users should 
                                     # be done without e-mail address
    step:
      type: acme
      name: ACME RA for Smallstep CM
      catype: private
      api: https://acme.example.com/acme/acme/directory
      url: https://example.com
      roots: null
      description: "ACME RA for Smallstep CM. Lorem Ipsum."
      logopath: "https://foo.bar/logo.png"
      daysRenewBeforeExpiry: 30
    tsec:
      type: legacy
      name: T-Sec Trust Center
      catype: public
      roots: https://www.telesec.de/en/root-program/root-program/overview/
      description:  "Telesec Trust Center. Lorem Ipsum."
      logopath: "https://foo.baz/logo.png"
#AutoDNS & DNS-01 validation
#DNS provider implementations shall support zone nesting
#For legacy CA a CSR template can be assigned to each rtzn implicitly by convention
rtzn:
  - root: foo.example.org. #Rootzones always have a dot at the end
    autodns: null
    acmedns: dns3l
    ca:
      - step
      - tsec
  - root: bar.example.com.
    autodns: infblxA
    acmedns: dns3l
    ca: ['*'] 
  - root: foo.bar.example.com.
    autodns: infblxB
    acmedns: dns3l
    ca: ['*']
db:
  # Since database providers are not 100% abstracted in Go, only "mysql" is supported
  # at the moment. "sqlite3" might work but is unsupported.
  type: mysql

  # SQL data source string
  # === For mysql:
  # MySQL data source name (DSN)
  # Reference: https://github.com/go-sql-driver/mysql#dsn-data-source-name
  # ?parseTime=true MUST be added to the end, otherwise errors will occur
  # === For sqlite3:
  # Database file name
  url: user:password@tcp(192.168.0.1)/dns3ld?parseTime=true

  # This prefix is added to every table created/used
  dbprefix: dns3l
auth:

  #OIDC token issue
  issuer: https://token.issuer.url.de/auth

  #OIDC Client ID
  client_id: cli-app

  #Disables authentication, everyone can use the API
  authn_disabled: false

  #Disables authorization if authn is enabled, everybody who is logged in can do anything
  authz_disabled: false
  
  #When contacting the auth provider service, SSL cert verification is disabled
  http_insecure_skip_verify: true

  #If set to true, information in the claims is dumped to the log
  debug_claims: false

  #User e-mail address used (for ACME, persistency) if authn is disabled
  authn_disabled_email: foo@telekom.de

  #If your auth provider cannot provide you with the "groups" list in the token
  #claims, use this as a workaround to inject values to a user's list. Not suitable
  #for scalable LDAP auth, but sufficient for testing setups.
  inject_groups:

    #First level: e-mail address
    kilgore@kilgore.trout:
      #List of groups to inject
      - read #allow read actions
      #- write #allow write actions
      - foo.example.org.
      - bar.example.com.

  # Prefix of the groups in the claim. Groups without the given prefix will be ignored.
  # The prefix is stripped from the group to render the allowed root zone
  # The prefix also applies to the "read" and "write" groups (i.e. "<prefix>write")
  # Default: ""
  groups_prefix: dns3l_

  # Replace all occurrences of single '_' with  '.'
  # Useful if your authz provider does not support groups with a '.' in the name
  # This replacement is done *after* the goups prefix has been stripped (see above).
  # If you have underscores in your root zone, use "__" (double underscore) and they will
  # be replaced by a single underscore.
  groups_replace_dot: false

  # === Example for groups_prefix: dns3l_ and groups_replace_dot: true 
  # "dns3l_foo_bar_com" will allow domain "foo.bar.com"
  # "dns3l_under__score_corp" will allow domain "under_score.corp"
  # "dns3l_read" will allow read access

renew:
  #Renewal jobs start every day at the specified time (UTC).
  jobStartTime: 01:00

  #Renewal jobs are scheduled so they are over after the given duration.
  maxDuration: 6h

  #Not more than the given amount of jobs is scheduled per day in order to
  #avoid overload and suffering from rate limits. If the limit is hit, a warning
  #is set in the log.
  limitPerDay: 2048

  #Additionally, last-resort warnings are logged if certificates are about to 
  #expire, e.g. if they have not been renewed for any reason.
  daysWarnBeforeExpiry: 10
