url: https://foobar.example.com
adminemail:
  - admin1@example.com
  - admin2@example.net
dns: # DNS service providers
  providers:
    infblxA: # Infoblox NIOS over WAPI
      type: infblx
      name: Infoblox A
      #url: https://infoblox.example.com/wapi/v2.10
      host: foo.bar2.local
      port: 12345
      version: v2.10
      auth: #endpoint specific
        user: username
        pass: password
    infblxB:
      type: infblx
      name: Infoblox B
      host: foo.bar.local
      port: 1234
      version: v2.8
      auth:
        user: username
        pass: password
    dns3l:
      type: otc # Open Telekom Cloud (OTC) DNS
      name: DNS3L Labs Inc. OTC tenant
      auth:
        authurl: https://iam.eu-de.otc.t-systems.com/v3
        projectname: #omitted
        projectid: #omitted
        ak: access key ID
        sk: secret access key
      os-region: eu-de
# somepdns:
#   type: pdns # PowerDNS AS
#   ...
ca: #ACME and none ACME CA
  providers:
    le: #Add least /directory to endpoint URL
      type: acme
      name: Let's Encrypt
      catype: public
      url: https://acme-v02.api.letsencrypt.org/directory
      roots: https://letsencrypt.org/certificates/
      description: "Let's Encrypt Official"
      logopath: "https://foo.bar/logo.png"
      checkNameservers:
       - 80.158.48.19:53
       - 93.188.242.252:53
      daysRenewBeforeExpiry: 30
    tsec-staging:
      type: acme
      name: T-Sec Trust Center ACME Staging
      catype: public
      url: https://acme.npp.test.telesec.de/v2/directory
      auth: #CA specific
        account: Account Id
        key: EAB KeyId
        hmac: EAB HMAC
      roots: https://www.telesec.de/en/root-program/root-program/overview/
      description: "Telesec Trust Center ACME Staging"
      logopath: "https://bar.foo/logo.png"
      daysRenewBeforeExpiry: 30
    step:
      type: acme
      name: ACME RA for Smallstep CM
      catype: private
      url: https://acme.example.com/acme/acme/directory
      roots: null
      description: "ACME RA for Smallstep CM. Lorem Ipsum."
      logopath: "https://foo.bar/logo.png"
      daysRenewBeforeExpiry: 30
    tsec:
      type: legacy
      name: T-Sec Trust Center
      catype: public
      roots: https://www.telesec.de/en/root-program/root-program/overview/
      description:  "Telesec Trust Center. Lorem Ipsum."
      logopath: "https://foo.baz/logo.png"
#AutoDNS & DNS-01 validation
#DNS provider implementations shall support zone nesting
#For legacy CA a CSR template can be assigned to each rtzn implicitly by convention
rtzn:
  - root: foo.example.org. #Rootzones always have a dot at the end
    autodns: null
    acmedns: dns3l
    ca:
      - step
      - tsec
  - root: bar.example.com.
    autodns: infblxA
    acmedns: dns3l
    ca: ['*'] 
  - root: foo.bar.example.com.
    autodns: infblxB
    acmedns: dns3l
    ca: ['*']
db:
  type: mysql
  url: user:password@tcp(192.168.0.1)/dns3ld?parseTime=true
  dbprefix: dns3l
auth:
  issuer: https://token.issuer.url.de/auth
  client_id: cli-app
  authn_disabled: false
  authz_disabled: false
  http_insecure_skip_verify: true
  claims_debug: true
  authn_disabled_email: foo@telekom.de
  inject_groups:
    kilgore@kilgore.trout:
      - read
      #- write
      - foo
      - test.otc.dta4.de.
renew:
  jobStartTime: 01:00
  maxDuration: 6h
  limitPerDay: 2048
  daysWarnBeforeExpiry: 120

