url: {{.Env.DNS3L_URL}}
adminemail:
{{- range $i, $e := jsonQuery .Env.DNS3L_EMAIL "."}}
  - {{ $e }}
{{- else}}
  - foo@example.com
{{- end}}

dns: # DNS service providers
  providers:
    # infblx:
    #   type: infoblox # Infoblox NIOS over WAPI
    #   name: Infoblox
    #   host: foo.bar.local
    #   port: 1234
    #   version: v2.8
    #   dnsview: my-dnsview
    #   auth:
    #     user: username
    #     pass: password
    #   sslverify: false
    otc:
      type: otc # Open Telekom Cloud (OTC)
      name: OTC
      auth:
        authurl: https://iam.{{.Env.DNS_OTC_REGION}}.otc.t-systems.com/v3
        projectname: # omitted
        projectid: # omitted
        ak: {{.Env.DNS_OTC_AK}}
        sk: {{.Env.DNS_OTC_SK}}
      os-region: {{.Env.DNS_OTC_REGION}}

ca:
  providers:
    le:
      type: acme
      name: "Let's Encrypt"
      catype: public
      api: https://acme-v02.api.letsencrypt.org/directory
      url: https://letsencrypt.org
      roots: https://letsencrypt.org/certificates/
      description: "The most popular public ACME CA worldwide."
      logopath: "http://localhost/le.png"
      daysRenewBeforeExpiry: 30
      enabled: true
    les:
      type: acme
      name: "Let's Encrypt Staging"
      catype: public
      api: https://acme-staging-v02.api.letsencrypt.org/directory
      url: https://letsencrypt.org/docs/staging-environment
      roots: https://letsencrypt.org/certificates/
      description: "The most popular public ACME CA worldwide."
      logopath: "http://localhost/le.png"
      daysRenewBeforeExpiry: 30
      enabled: true
    scm:
      type: acme
      name: "Smallstep CM RA"
      catype: private
      api: {{.Env.STEP_RA_URL}}/acme/acme/directory
      url: https://smallstep.com/certificates/
      roots: null
      description: "A CAaaS powered by Smallstep Labs, Inc."
      logopath: "http://localhost/ss.png"
      daysRenewBeforeExpiry: 30
      enabled: false ###

rtzn:{{range $i, $e := jsonQuery .Env.DNS3L_RTZN "."}}
  - root: {{printf "%s" $e.root}}.
    autodns: {{printf "%s" $e.autodns}}
    acmedns: {{printf "%s" $e.acmedns}}
    ca:{{range $j, $c := $e.ca}}
      - '{{printf "%s" $c}}'{{end}}{{end}}

db:
  type: mysql
  url: {{.Env.DNS3L_DB_USER}}:{{.Env.DNS3L_DB_PASS}}@tcp({{.Env.DNS3L_DB_HOST}}:3306)/{{.Env.DNS3L_DATABASE}}?parseTime=true
  dbprefix: dns3l

auth:
  issuer: {{.Env.DNS3L_AUTH_URL}}
  client_id: dns3l-api
  authn_disabled: false
  authz_disabled: true
  http_insecure_skip_verify: true
  claims_debug: true
  authn_disabled_email: foo@example.com ### ???
  groups_prefix: DNS3L_
  groups_replace_dot: true

renew:
  jobStartTime: 01:00
  maxDuration: 6h
  limitPerDay: 2048
  daysWarnBeforeExpiry: 120
