FROM golang:1.24-alpine@sha256:8f8959f38530d159bf71d0b3eb0c547dc61e7959d8225d1599cf762477384923 AS build

ARG TARGETARCH=amd64

WORKDIR /go/build
RUN apk add --no-cache \
    bash \
    make
COPY . .
RUN GOARCH=${TARGETARCH} make cli

FROM alpine:3.22@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412

LABEL org.opencontainers.image.title="dns3lcli"
LABEL org.opencontainers.image.description="DNS3L command-line API client"
LABEL org.opencontainers.image.version=0.0.0

RUN apk --update upgrade && \
    apk add --no-cache ca-certificates && \
    rm -rf /var/cache/apk/*

COPY --from=build /go/build/dns3lcli /usr/local/bin/dns3lcli

ENTRYPOINT ["/usr/local/bin/dns3lcli"]
