#!/usr/bin/env sh

# Docker launcher (not an entrypoint), currently only used
# to run test in existing containers

set -e

case "$1" in 
  golang-alpine)
    echo '@community https://dl-cdn.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories
    apk update
    apk add mariadb step-cli step-certificates@community
    echo "uut:x:1000:1000:uut:/go:/bin/ash" >> /etc/passwd
    su uut -c "cd /workdir; go run test/main.go $2"
    ;;
  *)
    echo "No command given."
    exit 1
esac
