name: comptest
on: push

jobs:
  comptest:
    runs-on: ubuntu-latest
    container:
      image: golang:1.19-alpine
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run
        run: |
          docker/run-in-docker golang-alpine
